### ISSUE TITLE
冻结的（用户安装的）app未被备份

### ISSUE THREAD

**Issue by TomKing062** [YAWAsau/backup_script#100]
由于使用了thanox的自动冻结功能，备份前生成的applist内直接没有显示这几个app

**Comment by YAWAsau** [comment]
方便來我Q測試嗎？我修好了

**Comment by YAWAsau** [comment]
> 由于使用了thanox的自动冻结功能，备份前生成的applist内直接没有显示这几个app

腳本已經更新 你試試看
