### ISSUE TITLE
大佬，为什么会这样啊

### ISSUE THREAD

**Issue by loser026** [YAWAsau/backup_script#13]
![IMG_20210920_002834](https://user-images.githubusercontent.com/76159133/133935355-ba9fc700-1f2f-4b08-b691-4a3d6237d2a8.jpg)
![IMG_20210920_002812](https://user-images.githubusercontent.com/76159133/133935357-7a6eb159-bd8e-47ae-b866-964db0b4a771.jpg)

**Comment by YAWAsau** [comment]
data/backup_tools刪除再執行一次就好了

**Comment by loser026** [comment]
不行啊，我昨天晚上试了好几次

**Comment by YAWAsau** [comment]
976613477加我群 我明天給你搞定
