### ISSUE TITLE
appname.sh不能正常检测应用包名

### ISSUE THREAD

**Issue by ajdgsu** [YAWAsau/backup_script#14]
我的手机上这个软件(https://www.lanzoux.com/igdzlu9k8na)

在使用appname.sh获取包名时每次都会被写入Apkname.txt(即使它已经在Apkname.txt里了)，如图:
![Screenshot_20210920-123545_MT Manager](https://user-images.githubusercontent.com/45306865/133957521-08a458b4-2594-4fd6-8c7f-d06a93be3b09.jpg)

**Comment by YAWAsau** [comment]
修復中
