### ISSUE TITLE
最新版(9.1)不能正常工作

### ISSUE THREAD

**Issue by ajdgsu** [YAWAsau/backup_script#15]
报错如下:
![Screenshot_20210920-125333_MT Manager](https://user-images.githubusercontent.com/45306865/133958346-291b46db-f0f8-4d7d-9883-4a968a024d3e.jpg)

**Comment by ajdgsu** [comment]
目前9.4版仍然有报错，但至少能备份了
![Screenshot_20210921-215600_MT Manager](https://user-images.githubusercontent.com/45306865/134184306-250bd885-8598-4513-90b5-acea9ef97942.jpg)

**Comment by YAWAsau** [comment]
+我qq群976613477

**Comment by ajdgsu** [comment]
最新版(9.6仍然会报错)
![Screenshot_20211003-194637_MT Manager](https://user-images.githubusercontent.com/45306865/135752259-7ce68d1a-99cc-4b83-9fb6-a2b8cd46190d.jpg)

还有我加你的qq群并没有同意，我的qq号是1637448903

**Comment by YAWAsau** [comment]
沒看到
