### ISSUE TITLE
时不时吐口痰

### ISSUE THREAD

**Issue by 1Yie** [YAWAsau/backup_script#2]
十分恶臭，千万别用，大家吐口痰再走。

**Comment by YAWAsau** [comment]
我草泥馬的給你全家揚了給你貓殺了燉湯 ctmb全家都燉了

**Comment by 1Yie** [comment]
> 我草泥马的给你全家扬了给你猫杀了炖汤ctmb全家都炖了

呜呜呜，你再骂？
