### ISSUE TITLE
貌似这次更新，MIUI又有一些应用没被排除

### ISSUE THREAD

**Issue by MAT-OUT** [YAWAsau/backup_script#27]
com.miui.analytics
com.xiaomi.scanner
com.miui.compass
com.miui.cleanmaster
com.miui.weather2
好像之前版本不会，是排除逻辑改了吗。

**Comment by YAWAsau** [comment]
我在檢查看看

**Comment by YAWAsau** [comment]
你有沒有我的群 測試下

**Comment by MAT-OUT** [comment]
> 
> 
> 你有沒有我的群 測試下

none...

**Comment by YAWAsau** [comment]
点击链接加入群聊【臭高雄的窩】：https://jq.qq.com/?_wv=1027&k=avi9iIjh

**Comment by MAT-OUT** [comment]
> 
> 
> 点击链接加入群聊【臭高雄的窩】：https://jq.qq.com/?_wv=1027&k=avi9iIjh

哦，完了，我不用QQ

**Comment by YAWAsau** [comment]
最新版本解決了

**Comment by MAT-OUT** [comment]
> 最新版本解決了

感谢
