### ISSUE TITLE
请问双开应用怎么备份，安装包和数据，主要是数据

### ISSUE THREAD

**Issue by One010101** [YAWAsau/backup_script#29]
请问双开应用怎么备份，安装包和数据，主要是数据

**Comment by YAWAsau** [comment]
目前還沒規劃寫

**Comment by One010101** [comment]
> 目前還沒規劃寫

还有两个问题
1. 请问这个备份是增量备份吗，还是覆盖掉原来的？
2. 第一次全部备份后，第二次想单独备份一个app及数据，把其他的APP都用`#` 注释掉，可以成功备份吗，备份的这个app是覆盖还是增量？

**Comment by YAWAsau** [comment]
1,覆蓋備份
2.也是覆蓋

**Comment by YAWAsau** [comment]
> > 目前還沒規劃寫
> 
> 还有两个问题
> 
> 1. 请问这个备份是增量备份吗，还是覆盖掉原来的？
> 2. 第一次全部备份后，第二次想单独备份一个app及数据，把其他的APP都用`#` 注释掉，可以成功备份吗，备份的这个app是覆盖还是增量？

**Comment by YAWAsau** [comment]
> 請問雙開應用怎麼備份，安裝包和數據，主要是數據

好消息 我寫好了 可以試試看了
