### ISSUE TITLE
有一個需求

### ISSUE THREAD

**Issue by One010101** [YAWAsau/backup_script#30]
我想只備份自定義的文件夾，於是我把media什麼什麼的改為1，然後把applist裡面的app全部用#注釋掉，然後開始備份，但是提示applist為空或者全部注釋。

**Comment by One010101** [comment]
我又測試了一下是增量的。我只要在applist中添加備份一個app，最少一個，才能備份自定義文件夾，要是直接備份文件夾就好了

**Comment by YAWAsau** [comment]
安排

**Comment by One010101** [comment]
> 安排
啥时候安排啊？半个月了٩(๑•̀ω•́๑)۶

**Comment by YAWAsau** [comment]
阿哲都忘記了

**Comment by YAWAsau** [comment]
已經好了可以更新了

**Comment by One010101** [comment]
> 已經好了可以更新了

感谢，确实好用
