### ISSUE TITLE
能否将忽略的软件加入applist默认关闭？

### ISSUE THREAD

**Issue by Mr54233** [YAWAsau/backup_script#33]
米家和小爱同学lite，小米运动每次都会被忽略，每次刷新应用列表都要重新手动加到applist里

**Comment by YAWAsau** [comment]
有個問題是 因為廠商放了很多自帶應用在裡面 我沒辦法知道這是默認的還是第三方 所以目前是用關鍵詞檢查 我設置白名單？

**Comment by YAWAsau** [comment]
請把包名給我

**Comment by Mr54233** [comment]
米家&nbsp;com.xiaomi.smarthome
推送服务&nbsp;com.xiaomi.xmsf
小米运动&nbsp;com.xiaomi.hm.health
小米文档查看器（WPS定制）&nbsp;cn.wps.moffice_eng.xiaomi.lite
小爱同学&nbsp;com.xiaomi.xiaoailite


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月23日(周日) 下午3:56
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [YAWAsau/backup_script] 能否将忽略的软件加入applist默认关闭？ (Issue #33)




 
請把包名給我
 
&mdash;
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by YAWAsau** [comment]
已經完善

**Comment by YAWAsau** [comment]
如果還有包名記得提Issues
