### ISSUE TITLE
单应用多备份需求

### ISSUE THREAD

**Issue by targaryener** [YAWAsau/backup_script#34]
抱歉，平板不方便打繁体哈

你好，我有一个需求，就是单个应用生成多个备份，而后根据需要选择恢复对应的备份

不知道有此类需求的人群多不多，实现的成本会不会很大，希望开发大大可以评估一下哦

**Comment by YAWAsau** [comment]
可是這樣空間會佔用很多喔

**Comment by kchtin** [comment]
是的， 我也有这个需求。 目前才用的是修改文件夹方式。

而且是否支持备份单一 app呢
