### ISSUE TITLE
简体版前几个版本有个bug已修复

### ISSUE THREAD

**Issue by Petit-Abba** [YAWAsau/backup_script#38]
就是好像没有把那个.conf文件简体化还是咋回事，不过我已经修好了🌚

**Comment by Petit-Abba** [comment]
还有把30分钟自动更新更改为15分钟了（不过按照action的尿性可能会延迟几分钟）😂

**Comment by Petit-Abba** [comment]
![Screenshot_2022-02-09-03-20-28-427_bin mt plus](https://user-images.githubusercontent.com/79740011/153059993-125d0c5c-542c-43b9-915d-a7ff81ba9311.jpg)
3gb备份用时1分钟31秒，还得是你呀小高雄！

**Comment by YAWAsau** [comment]
你媽的 你去哪裡ㄌ 都找不到人

**Comment by Petit-Abba** [comment]
> 

退安了，时不时上git摸摸鱼

**Comment by YAWAsau** [comment]
那QQ呢 幹 也不上

**Comment by kudoushinnyan** [comment]
> 你媽的 你去哪裡ㄌ 都找不到人

(有一腿)
