### ISSUE TITLE
几点建议

### ISSUE THREAD

**Issue by ghostshutter** [YAWAsau/backup_script#4]
1、希望有方法独立运行（尝试用Mix文件管理器执行，结果备份到自己直接崩了），而且依赖于MT管理器也不是个事（目前为了它在本地留了个终端apk）
2、希望能备份/导出联系人vcf文件(我知道谷歌能还原，但是国内这情况有点麻烦，而且作为一个备份软件这算基础功能吧…)
就个人使用而言，这备份有点硬核（），但是确实有够简单粗暴的，有点东西

**Comment by ghostshutter** [comment]
3、虽然没试过，备份还原能否在REC的终端里执行？

**Comment by YAWAsau** [comment]
你好 原因是因為備份需要殺死指定的apk包名進行數據的備份 這點我會修復 關於twrp內恢復不可以，因為關機狀態無法進行pm install且需要獲取packages.list的pid進入權限設置 目前能在termux mt備份沒問題

**Comment by ghostshutter** [comment]
还遇到个bug,小米运动（com.xiaomi.hm.health）不知道为什么没被录进去（感觉有点离谱）

**Comment by YAWAsau** [comment]
默認屏蔽全部帶Xiaomi包名 不是bug

**Comment by ghostshutter** [comment]
没看代码（），现在自己注释了（）
没啥问题了，等波更新（就为运行个这装个termux还是觉得有点emmmmm）
