### ISSUE TITLE
无法写入应用列表到文件

### ISSUE THREAD

**Issue by asky88** [YAWAsau/backup_script#40]
如题，运行getlist.sh时提示正常，但实际applist.txt无数据

![Screenshot_20220223-085212](https://user-images.githubusercontent.com/82694610/155245452-26ffd493-eb62-4103-b0a2-b017ff231c35.png)
![Screenshot_20220223-085220](https://user-images.githubusercontent.com/82694610/155245278-ed828456-36b5-47e8-aeb5-fbe7b3bdc775.png)
![Screenshot_20220223-085229](https://user-images.githubusercontent.com/82694610/155245285-3e68df81-5bb4-41a1-aa84-586aab56ae26.png)
终端为原版termux

**Comment by YAWAsau** [comment]
已經修復
