### ISSUE TITLE
求救！！提示zstd解壓失敗，已過世。。

### ISSUE THREAD

**Issue by msczhen** [YAWAsau/backup_script#42]
请看图吧！！
![Screenshot_2022-03-09-18-09-21-002_bin mt plus](https://user-images.githubusercontent.com/101259958/157435718-a07a3a92-4cd8-4fec-927f-9baa2f99a53a.jpg)

**Comment by wfinewy** [comment]
兄弟  我也遇到这种情况 解决了吗
