### ISSUE TITLE
請問如何備份系統設定、wifi設定、簡訊、桌面佈局？

### ISSUE THREAD

**Issue by BenzLeung** [YAWAsau/backup_script#44]
如題，昨日恢復出廠後使用本腳本，順利恢復了所有第三方app，然而發現仍然須手工進行各種系統偏好設定，手工重設家庭和公司wifi，手工整理桌面圖標……

於是請問大佬，本腳本是不是把某些系統app的包名加入就可以恢復系統設定、wifi設定、簡訊、桌面佈局？

**Comment by YAWAsau** [comment]
系統部分有機率去世

**Comment by BenzLeung** [comment]
> 系統部分有機率去世

没有看懂……

**Comment by GitHub-Stock** [comment]
> 好

这个使用系统自带的备份兼容性会更好

**Comment by GitHub-Stock** [comment]
> 如題，昨日恢復出廠後使用本腳本，順利恢復了所有第三方app，然而發現仍然須手工進行各種系統偏好設定，手工重設家庭和公司wifi，手工整理桌面圖標……
> 
> 於是請問大佬，本腳本是不是把某些系統app的包名加入就可以恢復系統設定、wifi設定、簡訊、桌面佈局？

这个使用系统自带的备份兼容性会更好

**Comment by BenzLeung** [comment]
> 

有道理
