### ISSUE TITLE
(有個問題困惑好久, 在備份的主目錄已經備份了一個MT管理器了, 為啥還要再備份一個MT管理器的資料夾)

### ISSUE THREAD

**Issue by KudouShinnyan** [YAWAsau/backup_script#47]
(感覺沒必要備份兩個主程序, 然後MT管理器好像也沒備份data的需求)

**Comment by GitHub-Stock** [comment]
比如手机双清后，手机里是没有MT管理器App的，这时候又没有网络，这时候就可以直接调用手机自带文件管理安装mt管理器，然后恢复数据

**Comment by GitHub-Stock** [comment]
> (感覺沒必要備份兩個主程序, 然後MT管理器好像也沒備份data的需求)

比如手机双清后，手机里是没有MT管理器App的，这时候又没有网络，这时候就可以直接调用手机自带文件管理安装mt管理器，然后恢复数据

**Comment by GitHub-Stock** [comment]
> (感覺沒必要備份兩個主程序, 然後MT管理器好像也沒備份data的需求)

mt管理器我存的有很多书签和ftp，所以备份data对我来说是有必要的

**Comment by YAWAsau** [comment]
> （然後MT管理器好像沒有需要備份數據的需求）

你動點腦子就知道了
