### ISSUE TITLE
备份Apk失败,，过世了

### ISSUE THREAD

**Issue by 17-233** [YAWAsau/backup_script#48]
![fe8de110c7ccd47165798d8aa64f512](https://user-images.githubusercontent.com/78686264/167972374-e2086718-5e4c-4ac7-ab00-b196b6150abb.jpg)
删过backup_tools还是这样

**Comment by YAWAsau** [comment]
你檔案壞了 重新下載一個備份腳本就好

**Comment by 17-233** [comment]
> 你档案坏了重新下载一个备份脚本就好了

搞好啦
谢谢
