### ISSUE TITLE
備份設置裡面，備份完成後啟動應用（添加包名後無法自啟動）

### ISSUE THREAD

**Issue by GitHub-Stock** [YAWAsau/backup_script#49]
mi10 pro miui13

**Comment by YAWAsau** [comment]
收到 我會看看

**Comment by GitHub-Stock** [comment]
太好了，大佬辛苦了


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月26日(周四) 凌晨0:10
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [YAWAsau/backup_script] 備份設置裡面，備份完成後啟動應用（添加包名後無法自啟動） (Issue #49)




  
mi10 pro miui13
  
已經修復 下次推送
 
&mdash;

**Comment by YAWAsau** [comment]
已經更新

**Comment by GitHub-Stock** [comment]
更新后，这个bug又复现了

**Comment by YAWAsau** [comment]
Gg 我發現了
