### ISSUE TITLE
unzip: can't open [.zip]

### ISSUE THREAD

**Issue by GitHub-Stock** [YAWAsau/backup_script#50]
执行脚本时，有一行这个unzip: can't open [.zip]，是属于报错吗？会不会对备份的数据造成影响？

**Comment by YAWAsau** [comment]
有圖嗎

**Comment by GitHub-Stock** [comment]
> 有圖嗎
![Screenshot_2022-05-26-11-31-40-062_bin mt plus](https://user-images.githubusercontent.com/35029753/170410489-a9a9a7d5-b28e-40e2-85a3-fd82c766f4e4.png)

**Comment by YAWAsau** [comment]
> > 有圖嗎
> > ![Screenshot_2022-05-26-11-31-40-062_bin mt plus](https://user-images.githubusercontent.com/35029753/170410489-a9a9a7d5-b28e-40e2-85a3-fd82c766f4e4.png)

已經推送並修復

**Comment by GitHub-Stock** [comment]
> > > 有圖嗎
> > > ![Screenshot_2022-05-26-11-31-40-062_bin mt plus](https://user-images.githubusercontent.com/35029753/170410489-a9a9a7d5-b28e-40e2-85a3-fd82c766f4e4.png)
> 
> 已經推送並修復

真滴效率
