### ISSUE TITLE
在Android12.1上无法设置应用权限

### ISSUE THREAD

**Issue by e5u** [YAWAsau/backup_script#54]
![Screenshot_20220630-174448_MT管理器](https://user-images.githubusercontent.com/53000648/176647171-c17b44fe-0c98-4e0c-b8f0-062f5ee2825d.png)

**Comment by YAWAsau** [comment]
selinux問題 暫時無法解決

**Comment by e5u** [comment]
在运行脚本时关闭SELinux会不会得到解决呢？

**Comment by YAWAsau** [comment]
可以
