### ISSUE TITLE
有没有可能支持云端备份?

### ISSUE THREAD

**Issue by yizhimengxin2233** [YAWAsau/backup_script#57]
有没有可能支持自动上传备份文件至onedrive,webdav,或者天翼云盘，阿里云盘之类的。
最好先询问用户，提供一个每备份完一个app就上传然后删除备份文件的选项。
验证文件之类的可以另外存一个数据库来保存md5之类的。
然后再警告用户不要删除文件夹什么的。
一般来说文件就都不会被更改。
上面这个流程是swiftbackup的，不知道实现难度有多大，抱歉

**Comment by YAWAsau** [comment]
Webdav我實現過 但是速度很慢 還有腳本實現還是有點困難的 curl部分設備會出現問題,另外驗證我是直接針對tar的壓縮-T選項去驗證 所以壞包問題會提示

**Comment by yizhimengxin2233** [comment]
> Webdav我實現過 但是速度很慢 還有腳本實現還是有點困難的 curl部分設備會出現問題,另外驗證我是直接針對tar的壓縮-T選項去驗證 所以壞包問題會提示

但是还是希望加上这么一个选项，使用webdav备份的人肯定也不会在乎速度了
