### ISSUE TITLE
备份及解压时user数据无法读写

### ISSUE THREAD

**Issue by ClayTT** [YAWAsau/backup_script#58]
![Screenshot_2022-08-31-20-46-45-795_com android settings](https://user-images.githubusercontent.com/49552414/187682049-26d17166-ac17-48fe-98d2-a3de950b6379.jpg)
![Screenshot_2022-08-31-20-24-00-777_bin mt plus](https://user-images.githubusercontent.com/49552414/187682076-a9117d3d-3d6a-4cdc-a479-f4b96d0b9539.jpg)
![Screenshot_2022-08-31-20-49-47-732_bin mt plus](https://user-images.githubusercontent.com/49552414/187682179-cb681aeb-8033-439b-93cf-a5bfeeb5e203.jpg)

**Comment by YAWAsau** [comment]
方便打包一份沒隱私的備份上來我試試看嗎？

**Comment by ClayTT** [comment]
[VMOS助手.zip](https://github.com/YAWAsau/backup_script/files/9466005/VMOS.zip)

**Comment by ClayTT** [comment]
[VMOS助手.zip](https://github.com/YAWAsau/backup_script/files/9466013/VMOS.zip)
vmos助手

**Comment by YAWAsau** [comment]
尷尬
![Uploading Screenshot_20220901-174410_MT_Manager.png…]()

**Comment by ClayTT** [comment]
或许和miui系统有关？

**Comment by ClayTT** [comment]
我是否还有其他可以提供帮助的方式

**Comment by ClayTT** [comment]
说文件夹不存在，无法恢复，解压失败
![Screenshot_2022-09-01-19-26-08-699_bin mt plus](https://user-images.githubusercontent.com/49552414/187903175-86767ad3-a32e-40db-84bc-82aa3d4b149f.jpg)

**Comment by ClayTT** [comment]
在使用最新的备份脚本创建新的备份时和最开始一样还是检测不到user数据

**Comment by YAWAsau** [comment]
舊版本會嗎？

**Comment by ClayTT** [comment]
之前可以用的15.5.7，现在也不可以用了

**Comment by ClayTT** [comment]
miui版本回到了开发版8.24也不可以用，这是我最旧版本的包了

**Comment by YAWAsau** [comment]
那我也無解 第一次遇到
