### ISSUE TITLE
报错：未知的架构: armeabi-v7a

### ISSUE THREAD

**Issue by usrtax** [YAWAsau/backup_script#63]
oppen:/mnt/5t/backup # ./生成应用列表.sh
 -未知的架构: armeabi-v7a

<img width="460" alt="image" src="https://user-images.githubusercontent.com/110233389/201459526-7353081a-9ad7-4c20-b9fc-2fb24599d02d.png">

**Comment by YAWAsau** [comment]
什麼機子？

**Comment by usrtax** [comment]
x98 mini
https://item.taobao.com/item.htm?spm=a230r.1.14.16.348e6da9TyTwnr&id=674869281241&ns=1&abbucket=14#detail

**Comment by YAWAsau** [comment]
僅支持arm64

**Comment by chengnan049** [comment]
此 Issues 应被关闭
