### ISSUE TITLE
非0用户部分应用未检测到

### ISSUE THREAD

**Issue by chen2021-web** [YAWAsau/backup_script#67]
![Screenshot_20230215-224535_炼妖壶](https://user-images.githubusercontent.com/83762621/219060473-eb38b5b6-a550-4176-b6d6-67a07b57249a.png)
![Screenshot_20230215-224506_MT管理器](https://user-images.githubusercontent.com/83762621/219060522-e8ca3526-77e7-49de-baa1-a4840f606709.png)

**Comment by chen2021-web** [comment]
在这里像微信和tim就没有找到。

**Comment by chen2021-web** [comment]
望解决

**Comment by chen2021-web** [comment]
使用island

**Comment by chen2021-web** [comment]
手动修改应用列表文件后可以备份未检测到的应用，ls /data/user/10可以看到未检测到应用的包名

**Comment by YAWAsau** [comment]
已經搞定了 你試試看
