### ISSUE TITLE
请问这个备份脚本相比于swift backup和钛备份有什么特别的优点吗？

### ISSUE THREAD

**Issue by Rilomilo** [YAWAsau/backup_script#68]
现在已经有了很经典的备份app如swift backup和钛备份等，这些app有着更直观易用的UI，所以为什么要开发这个备份脚本呢？请问这个备份脚本相比于这些经典的备份app有什么特别的优点吗？

**Comment by YAWAsau** [comment]
備份速度與配置好後的簡易性 可在外接硬碟中使用 目前市面上的任何軟件備份恢復速度都比不過腳本
