### ISSUE TITLE
或许是bug？反馈&建议

### ISSUE THREAD

**Issue by v2jun** [YAWAsau/backup_script#69]
使用很多次这个脚本了，很好用，感谢作者的付出。

然后是我发现的一些问题&建议：
1、当将备份脚本放在U盘里时，无论脚本本身所处的文件夹层级如何，备份出来的 backup 文件夹始终都在U盘根目录下
2、将备份用户改成 999 时，备份出来的 backup 文件夹类的恢复设置默认依旧留空，如果直接执行脚本开始恢复，会恢复到主用户下，而不是 999 的分身用户里，需要手动将恢复 setting.conf 里的用户修改为 999 才能正常恢复到分身。这部分不算bug，我看了下 tool.sh，输出内容现在好像是直接写死的，这部分应该可以考虑优化下，体验上会更好一点

**Comment by YAWAsau** [comment]
了解 感謝你的建議反饋 遮些問題我換小米13的時候我會看看的 .......現在我在等待他的類原生發布
