### ISSUE TITLE
打算基于本脚本实现基于ssh的纯网络备份

### ISSUE THREAD

**Issue by zanjie1999** [YAWAsau/backup_script#70]
想问一下作者有没有这方面的计划，如果没有，并且没有问题的话我就开动

初步打算通过ssh pipe（也就是常说的管道 | ）直接将zstd输出的文件写到远程端，和从远程端读出来，通过pipe将流给到zstd解压

这样的话本地不需要有可用空间（不需要写到手机的硬盘中，寿命也省下来了），也可以解决otg因为手机是usb2.0特别慢的问题，将文件直接备份到nas或者路由器或者电脑上

**Comment by Bushrangers** [comment]
估计是没有这个打算，要做的话早就做了，支持你的想法现在就干起来

**Comment by zanjie1999** [comment]
好那我开搞

**Comment by YAWAsau** [comment]
進度如何？

**Comment by YAWAsau** [comment]
> 好那我開搞

進度如何

**Comment by zanjie1999** [comment]
> > 好那我開搞
> 
> 進度如何

时间不多，进度缓慢，不打算在一个脚本中同时实现云端和本地因为过于复杂容易出错，并且目前方案只支持密码登录ssh

**Comment by haytoo** [comment]
> 好那我开搞

进度如何了，有在GitHub上吗

**Comment by zanjie1999** [comment]
> > 好那我开搞
> 
> 进度如何了，有在GitHub上吗

目前情况是暂停，搞其他去了，对于需要将其简体中文化还需要大量的工作量

**Comment by YAWAsau** [comment]
> > > 好那我開搞
> > 
> > 
> > 詳細資料如何了，在GitHub上有嗎
> 
> 目前情況是暫停，搞其他的了，因為需要將其簡體中文還需要大量的工作量
> 
> 剛推一張最新的修改到倉庫裡，目前可能可以備份（壓縮可用），還原的邏輯還沒改好

腳本現在會自己翻譯自己了 不用搞

**Comment by YAWAsau** [comment]
你可以把ssh步驟跟思路理給我 你就不用爆改腳本了 我直接寫函數

**Comment by YAWAsau** [comment]
+個群可以討論

**Comment by zanjie1999** [comment]
> 你可以把ssh步驟跟思路理給我 你就不用爆改腳本了 我直接寫函數

群加了，简单的说就是这样实现的
备份
```
tar --checkpoint-action="ttyout=%T\r" -cf - *.apk | zstd | sshpass -p "$sshPwd" ssh -p $sshPort $sshUser@$sshHost cat > "$outputPath/apk.tar.zst"
```
还原
```
sshpass -p "$sshPwd" ssh -p $sshPort $sshUser@$sshHost cat "$tar_path" | tar --checkpoint-action="ttyout=%T\r" -I zstd -xmpf - -C "$TMPDIR"
```
实际上就是这样实现在远程端运行任意命令，并且把输出内容管道给本地运行的命令，或者反过来
```
sshpass -p "$sshPwd" ssh -p $sshPort $sshUser@$sshHost 命令
```
sshPwd 是 ssh密码
sshPort 是 ssh服务器地址
sshUser 是 ssh用户名

所需的ssh和sshpass的二进制文件在这里（arm64 Android shell环境测试可用）
https://github.com/zanjie1999/meBackup/tree/master/tools/bin

**Comment by YAWAsau** [comment]
> > 你可以把ssh步驟跟理給我你就不用爆改腳本了直接我寫函數
> 
> 群組加了，簡單的說就是這樣實現的 備份
> 
> ```
> tar --checkpoint-action="ttyout=%T\r" -cf - *.apk | zstd | sshpass -p "$sshPwd" ssh -p $sshPort $sshUser@$sshHost cat > "$outputPath/apk.tar.zst"
> ```
> 
> 還原
> 
> ```
> sshpass -p "$sshPwd" ssh -p $sshPort $sshUser@$sshHost cat "$tar_path" | tar --checkpoint-action="ttyout=%T\r" -I zstd -xmpf - -C "$TMPDIR"
> ```
> 
> 其實就是這樣實作在遠端運行任意命令，並且把輸出內容管道給本地運行的命令，或者反過來
> 
> ```
> sshpass -p "$sshPwd" ssh -p $sshPort $sshUser@$sshHost 命令
> ```
> 
> sshPwd 是 ssh 密碼 sshPort 是 ssh 伺服器位址 sshUser 是 ssh 使用者名
> 
> 需要的ssh和sshpass的二進位檔案在這裡（arm64 Android shell環境測試可用） https://github.com/zanjie1999/meBackup/tree/master/tools/bin

Ssh似乎不是靜態編譯？
CANNOT LINK EXECUTABLE "ssh": library "libcrypto.so.1.1" not found: needed by main executable

**Comment by zanjie1999** [comment]
> > > 你可以把ssh步驟跟理給我你就不用爆改腳本了直接我寫函數
> > 
> > 
> > 群組加了，簡單的說就是這樣實現的 備份
> > ```
> > tar --checkpoint-action="ttyout=%T\r" -cf - *.apk | zstd | sshpass -p "$sshPwd" ssh -p $sshPort $sshUser@$sshHost cat > "$outputPath/apk.tar.zst"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 還原
> > ```
> > sshpass -p "$sshPwd" ssh -p $sshPort $sshUser@$sshHost cat "$tar_path" | tar --checkpoint-action="ttyout=%T\r" -I zstd -xmpf - -C "$TMPDIR"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 其實就是這樣實作在遠端運行任意命令，並且把輸出內容管道給本地運行的命令，或者反過來
> > ```
> > sshpass -p "$sshPwd" ssh -p $sshPort $sshUser@$sshHost 命令
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > sshPwd 是 ssh 密碼 sshPort 是 ssh 伺服器位址 sshUser 是 ssh 使用者名
> > 需要的ssh和sshpass的二進位檔案在這裡（arm64 Android shell環境測試可用） https://github.com/zanjie1999/meBackup/tree/master/tools/bin
> 
> Ssh似乎不是靜態編譯？ CANNOT LINK EXECUTABLE "ssh": library "libcrypto.so.1.1" not found: needed by main executable

这个二进制文件来自termux，按file的输出是Android ndk编译的二进制文件，我在miui Android13纯Android shell中测试通过
![](https://github.com/YAWAsau/backup_script/assets/16502567/86c7fddf-fce4-43cf-8082-46f4e235d08c)

**Comment by YAWAsau** [comment]
這樣就無法....因為termux path環境變量就有定義 其他環境無法使用

**Comment by zanjie1999** [comment]
> 這樣就無法....因為termux path環境變量就有定義 其他環境無法使用

你看我上面那张图，就是你说的其他环境，如果你不信，那我还有下面这张
<img width="502" alt="image" src="https://github.com/YAWAsau/backup_script/assets/16502567/4acf05e1-f18d-4212-b284-1bb9b64dadec">
不存在环境变量定义

**Comment by YAWAsau** [comment]
> > 這樣就可以....因為termux路徑環境指標定義其他環境無法使用
> 
> 你看我上面那張圖，就是你說的其他環境，如果你不相信，那我還有下面這張 不存在環境變數定義 <img alt="影像" width="502" src="https://user-images.githubusercontent.com/16502567/284453648-4acf05e1-f18d-4212-b284-1bb9b64dadec.png">
> 
> 換台Android10手機嘗試 <img alt="影像" width="500" src="https://user-images.githubusercontent.com/16502567/284455307-69fedb74-ba53-4e6c-8a74-a9c19fce9121.png">

不是這個問題

**Comment by YAWAsau** [comment]
> > 這樣就可以....因為termux路徑環境指標定義了其他環境無法使用
> 
> 你看我上面那張圖，就是你說的其他環境，如果你不相信，那我還有下面這張 不存在環境變數定義 <img alt="影像" width="502" src="https://user-images.githubusercontent.com/16502567/284453648-4acf05e1-f18d-4212-b284-1bb9b64dadec.png">
> 
> 換台Android10手機嘗試 <img alt="影像" width="500" src="https://user-images.githubusercontent.com/16502567/284455307-69fedb74-ba53-4e6c-8a74-a9c19fce9121.png">

你先搞懂靜態編譯跟動態編譯差別

**Comment by shiqianwei0508** [comment]
这个就算能解决ssh命令静态编译的问题，恢复逻辑也不好搞，因为我要从一个纯净的啥也没有的系统中恢复所有应用，而ssh方式至少需要先安装一个ssh服务端或者客户端。

**Comment by zanjie1999** [comment]
> 这个就算能解决ssh命令静态编译的问题，恢复逻辑也不好搞，因为我要从一个纯净的啥也没有的系统中恢复所有应用，而ssh方式至少需要先安装一个ssh服务端或者客户端。

不啊，你家里没有路由器？没有Windows/Linux/macOS电脑吗？
只需要一个ssh服务端（Windows，Linux，macOS，Openwrt自带），客户端就是静态编译好的一个二进制文件，你就可以这种方式备份和恢复，并且备份的时候不会在本地产生备份文件，就算你手机空间只剩下几MB了也能备份，并且ssh传输是加密的，你甚至可以通过这种方式直接进行异地备份到另一处的Nas中
