### ISSUE TITLE
appinfo輸出失敗，请问如何处理？

### ISSUE THREAD

**Issue by hzwyjxy** [YAWAsau/backup_script#71]
显示两个ABORT后，appinfo输出失败了

**Comment by hzwyjxy** [comment]
设备是pixel4，安卓12，貌似无法获取到应用列表

**Comment by hzwyjxy** [comment]
Open_apps="$(appinfo -d "(" -ed ")" -o ands,pn -ta c 2>/dev/null)"

在shell里运行结果是abort

**Comment by hzwyjxy** [comment]
> 有截圖嗎

有的
![Screenshot_20230911-141548](https://github.com/YAWAsau/backup_script/assets/43065974/6155b6c5-d1ed-4065-b991-d01c53872728)

**Comment by hzwyjxy** [comment]
基于您脚本的https://github.com/XayahSuSuSu/Android-DataBackup

**Comment by hzwyjxy** [comment]
基于您脚本的这个开源Apphttps://github.com/XayahSuSuSu/Android-DataBackup

**Comment by hzwyjxy** [comment]
基于您脚本的这个开源App https://github.com/XayahSuSuSu/Android-DataBackup  我也试了，在pixel3和4上都是可用的。但是直接使用脚本只有pixel3上正常，pixel4上没法生成列表、备份or恢复数据，均会报错。pixel4就是官方工厂包安卓12环境，配magisk其他啥也没装，试了多台pixel4均复现了这个问题

**Comment by YAWAsau** [comment]
怪 magisk版最新的嗎

**Comment by hzwyjxy** [comment]
> 怪 magisk版最新的嗎

25.2 和26.2我都用过，26.2是最新的，应该不是magisk问题吧？

**Comment by YAWAsau** [comment]
最新版本可以在嘗試看看

**Comment by YAWAsau** [comment]
老哥 我可以搞定了生成失敗問題 方便來我群裡測試下嗎？
