### ISSUE TITLE
15.7.1备份微信过程中，微信自动重启，导致user数据出现变化

### ISSUE THREAD

**Issue by shiqianwei0508** [YAWAsau/backup_script#72]
15.7.1备份微信过程中，微信自动重启，导致user数据出现变化

- 暂时解决办法
```
备份过程中关闭微信的自启动
```

15.7.0没有这个问题，感觉上个版本的冻结还是有用的。

**Comment by YAWAsau** [comment]
了解，因為有人回報凍結有點問題 查看進程pid還在
