### ISSUE TITLE
能不能增加既不部分应用，又不备份数据的黑名单。

### ISSUE THREAD

**Issue by huxc573** [YAWAsau/backup_script#78]
发现appList.txt生成的应用包名，用“#”注释后，只有下一次生成列表会忽略该应用锁，如果两次点击"生成应用列表.sh"，相当于就没有忽略备份的应用了。
同时，可以增加重装应用的选项吗？即如果手机现有版本更高，或者签名不一致，卸载可以卸载应用后还原。

**Comment by YAWAsau** [comment]
我看看

**Comment by YAWAsau** [comment]
> 发现appList.txt生成的应用包名，用“#”注释后，只有下一次生成列表会忽略该应用锁，如果两次点击"生成应用列表.sh"，相当于就没有忽略备份的应用了。 同时，可以增加重装应用的选项吗？即如果手机现有版本更高，或者签名不一致，卸载可以卸载应用后还原。

已經搞定
![Screenshot_20231123-175443_MT管理器](https://github.com/YAWAsau/backup_script/assets/62833322/e4e5e3ed-b7b9-4021-95b8-2908020fad41)
![Screenshot_20231123-163349_MT管理器](https://github.com/YAWAsau/backup_script/assets/62833322/0d6e0d8c-499e-4044-bd61-19f32e41654f)
