### ISSUE TITLE
脚本可以支持在twrp/ofrp中备份数据吗？

### ISSUE THREAD

**Issue by ZhcnPanda** [YAWAsau/backup_script#79]
脚本可以支持在twrp/ofrp中备份数据吗？

**Comment by YAWAsau** [comment]
無

**Comment by YAWAsau** [comment]
> 脚本可以支持在twrp/ofrp中备份数据吗？

已經完成
![Screenshot_20231123-163349_MT管理器](https://github.com/YAWAsau/backup_script/assets/62833322/9eda6798-4bff-4bf3-a292-ea0ed658a96e)
![Screenshot_20231123-175443_MT管理器](https://github.com/YAWAsau/backup_script/assets/62833322/a61a9d93-965a-47c2-9411-8e195ae8bff2)
