### ISSUE TITLE
备份或恢复备份，均报错显示PV文件被更改或损毁

### ISSUE THREAD

**Issue by Hoha2333** [YAWAsau/backup_script#8]
这个是恢复备份的报错
![image](https://user-images.githubusercontent.com/61763722/130356040-5dfc9a46-0b36-4f54-afe6-d6af349f4c66.png)
这个是备份的报错
![image](https://user-images.githubusercontent.com/61763722/130356068-b72fbf03-f93e-47ac-a82c-7294dd205513.png)
下面这个是它报错的那个文件夹
![image](https://user-images.githubusercontent.com/61763722/130356119-e37a1e00-a764-46fa-a6ea-add82ac46e2d.png)

**Comment by Hoha2333** [comment]
解决了，在用FTP传电脑文件夹到手机时，可能出现了奇怪的bug。我这次重新下载项目，解压后将里面的tool文件夹和.sh文件覆盖原Backup文件夹，发现运行正常了。

**Comment by Hoha2333** [comment]
解决了，在用FTP传电脑文件夹到手机时，可能出现了奇怪的bug。我这次重新下载项目，解压后将里面的tool文件夹和.sh文件覆盖原Backup文件夹，发现运行正常了。

**Comment by YAWAsau** [comment]
要不要加群

**Comment by Hoha2333** [comment]
要

**Comment by YAWAsau** [comment]
976613477

> 要
