### ISSUE TITLE
不支持隐藏目录及文件的备份（以.开头的目录和文件）

### ISSUE THREAD

**Issue by stainge** [YAWAsau/backup_script#80]
有时候需要存一些git repo，但是.git目录丢失了就无法与远程repo同步了

**Comment by YAWAsau** [comment]
了解 已經發現了

**Comment by YAWAsau** [comment]
> 有时候需要存一些git repo，但是.git目录丢失了就无法与远程repo同步了

能進來我Q群測試下嗎

**Comment by YAWAsau** [comment]
> > > 有时候需要存一些git repo，但是.git目录丢失了就无法与远程repo同步了
> > 
> > 
> > 能進來我Q群測試下嗎
> 
> 加群啦，怎么测试？

群內@落葉淒涼 我才知道是誰
