### ISSUE TITLE
安卓 14 无法恢复

### ISSUE THREAD

**Issue by m512106824** [YAWAsau/backup_script#81]
![Uploading Screenshot_2024-01-18-08-08-22-45_9e8df3d0c7c1f50248b6ee043a653d26.jpg…]()

**Comment by m512106824** [comment]
![Uploading Screenshot_2024-01-18-08-08-22-45_9e8df3d0c7c1f50248b6ee043a653d26.jpg…]()

**Comment by YAWAsau** [comment]
我android14一切正常 另外你圖壞了
