### ISSUE TITLE
新的数据保存目录

### ISSUE THREAD

**Issue by chuangdi** [YAWAsau/backup_script#82]
一加8pro刷了superior OS13.1后，数据保存目录从原来的/data/data变成了/data_mirror/data_ce/null/0/，用脚本备份出现提示数据已遗失。脚本很好用，一直用的这个，希望能够改进。

**Comment by YAWAsau** [comment]
方便來我群內測試嗎 我過年搞

**Comment by chuangdi** [comment]
可以，怎么加群？

YAWAsau ***@***.***> 于 2024年2月7日周三 23:37写道：

**Comment by YAWAsau** [comment]
976613477

**Comment by YAWAsau** [comment]
759598673這個 那群被封了

**Comment by chuangdi** [comment]
Awesome, thanks for the update!

YAWAsau ***@***.***> 于 2024年3月6日周三 12:04写道：
