### ISSUE TITLE
［功能建议］解冻后继续运行脚本

### ISSUE THREAD

**Issue by huxc573** [YAWAsau/backup_script#91]
5.9.4版本解冻后停止脚本，貌似和Thanox Pro的冻结冲突。就会出现一直无法运行脚本的情况，只有在Thanox Pro中手动解冻所以应用后才能正常运行脚本。
因此，能否加个选项，解冻后继续运行脚本，或者直接和之前版本一样不检查冻结应用列表了。

**Comment by YAWAsau** [comment]
回家研究看看

**Comment by YAWAsau** [comment]
> 5.9.4版本解冻后停止脚本，貌似和Thanox Pro的冻结冲突。就会出现一直无法运行脚本的情况，只有在Thanox Pro中手动解冻所以应用后才能正常运行脚本。 因此，能否加个选项，解冻后继续运行脚本，或者直接和之前版本一样不检查冻结应用列表了。

我測試沒有這個問題..... 你有運行的截圖嗎 我看下

**Comment by tanmoumou252** [comment]
> > 5.9.4版本解冻后停止脚本，貌似和Thanox Pro的冻结冲突。就会出现一直无法运行脚本的情况，只有在Thanox Pro中手动解冻所以应用后才能正常运行脚本。 因此，能否加个选项，解冻后继续运行脚本，或者直接和之前版本一样不检查冻结应用列表了。
> 
> 我測試沒有這個問題..... 你有運行的截圖嗎 我看下

```
    [38;5;226m --通知:false    [0m
    [38;5;226m ----------------------SpeedBackup---------------------    [0m
    [38;5;226m -脚本路径:/storage/emulated/0/Download/speed-backupV15.9.4
 -已开机:0天8时31分10秒
 -执行时间:2024-08-05 18:22:30
 -busybox路径:/data/backup_tools/busybox
 -busybox版本:v1.36.1-osm0sis
 -appinfo版本:2024-02-09（111）
 -脚本版本:V15.9.4
 -管理器:45fa1fce:MAGISKSU
 -品牌:Redmi
 -型号:Redmi K30S 至尊纪念版(apollo)
 -闪存颗粒:WDC SDINFDK4-256G(UFS)
 -处理器:Qualcomm® Snapdragon™ 865
 -RAM: 
 -Android版本:13 SDK:33
 -内核:4.19.312-perf+
 -Selinux状态:严格
 -By@YAWAsau
 -Support: https://jq.qq.com/?_wv=1027&k=f5clPNC3
 -如果当初握住的不是硬币，而是勇者的手......    [0m
    [38;5;226m -系统语言环境:简体中文    [0m
    [38;5;177m -主用户:0    [0m
    [38;5;226m -当前操作为用户0    [0m
    [38;5;226m -已解冻被冻结应用    [0m
```
在此之后就没反应了,所谓冻结的应用,也没有被恢复. 

thanox用的是智能冻结,没开活检解冻的话会显示 `已被IT管理员禁止` 

在thanox里全部解冻以后,脚本就正常运行了 

大佬顺便说一下,在恢复的时候如果应用名单里有MT管理器,就会停止MT的运行,虽然最终还是可以恢复安装,但数据就恢复不了,需要手动解压覆盖,感觉默认排除掉MT的包名会更好些

**Comment by YAWAsau** [comment]
> > > 5.9.4版本解冻后停止脚本，貌似和Thanox Pro的冻结冲突。就会出现一直无法运行脚本的情况，只有在Thanox Pro中手动解冻所以应用后才能正常运行脚本。 因此，能否加个选项，解冻后继续运行脚本，或者直接和之前版本一样不检查冻结应用列表了。
> > 
> > 
> > 我測試沒有這個問題..... 你有運行的截圖嗎 我看下
> 
> ```
>     [38;5;226m --通知:false    [0m
>     [38;5;226m ----------------------SpeedBackup---------------------    [0m
>     [38;5;226m -脚本路径:/storage/emulated/0/Download/speed-backupV15.9.4
>  -已开机:0天8时31分10秒
>  -执行时间:2024-08-05 18:22:30
>  -busybox路径:/data/backup_tools/busybox
>  -busybox版本:v1.36.1-osm0sis
>  -appinfo版本:2024-02-09（111）
>  -脚本版本:V15.9.4
>  -管理器:45fa1fce:MAGISKSU
>  -品牌:Redmi
>  -型号:Redmi K30S 至尊纪念版(apollo)
>  -闪存颗粒:WDC SDINFDK4-256G(UFS)
>  -处理器:Qualcomm® Snapdragon™ 865
>  -RAM: 
>  -Android版本:13 SDK:33
>  -内核:4.19.312-perf+
>  -Selinux状态:严格
>  -By@YAWAsau
>  -Support: https://jq.qq.com/?_wv=1027&k=f5clPNC3
>  -如果当初握住的不是硬币，而是勇者的手......    [0m
>     [38;5;226m -系统语言环境:简体中文    [0m
>     [38;5;177m -主用户:0    [0m
>     [38;5;226m -当前操作为用户0    [0m
>     [38;5;226m -已解冻被冻结应用    [0m
> ```
> 
> 在此之后就没反应了,所谓冻结的应用,也没有被恢复.
> 
> thanox用的是智能冻结,没开活检解冻的话会显示 `已被IT管理员禁止`
> 
> 在thanox里全部解冻以后,脚本就正常运行了
> 
> 大佬顺便说一下,在恢复的时候如果应用名单里有MT管理器,就会停止MT的运行,虽然最终还是可以恢复安装,但数据就恢复不了,需要手动解压覆盖,感觉默认排除掉MT的包名会更好些

我乾脆把mt去掉備份名單 至於凍結我在想個辦法

**Comment by YAWAsau** [comment]
> > > 5.9.4版本解冻后停止脚本，貌似和Thanox Pro的冻结冲突。就会出现一直无法运行脚本的情况，只有在Thanox Pro中手动解冻所以应用后才能正常运行脚本。 因此，能否加个选项，解冻后继续运行脚本，或者直接和之前版本一样不检查冻结应用列表了。
> > 
> > 
> > 我測試沒有這個問題..... 你有運行的截圖嗎 我看下
> 
> ```
>     [38;5;226m --通知:false    [0m
>     [38;5;226m ----------------------SpeedBackup---------------------    [0m
>     [38;5;226m -脚本路径:/storage/emulated/0/Download/speed-backupV15.9.4
>  -已开机:0天8时31分10秒
>  -执行时间:2024-08-05 18:22:30
>  -busybox路径:/data/backup_tools/busybox
>  -busybox版本:v1.36.1-osm0sis
>  -appinfo版本:2024-02-09（111）
>  -脚本版本:V15.9.4
>  -管理器:45fa1fce:MAGISKSU
>  -品牌:Redmi
>  -型号:Redmi K30S 至尊纪念版(apollo)
>  -闪存颗粒:WDC SDINFDK4-256G(UFS)
>  -处理器:Qualcomm® Snapdragon™ 865
>  -RAM: 
>  -Android版本:13 SDK:33
>  -内核:4.19.312-perf+
>  -Selinux状态:严格
>  -By@YAWAsau
>  -Support: https://jq.qq.com/?_wv=1027&k=f5clPNC3
>  -如果当初握住的不是硬币，而是勇者的手......    [0m
>     [38;5;226m -系统语言环境:简体中文    [0m
>     [38;5;177m -主用户:0    [0m
>     [38;5;226m -当前操作为用户0    [0m
>     [38;5;226m -已解冻被冻结应用    [0m
> ```
> 
> 在此之后就没反应了,所谓冻结的应用,也没有被恢复.
> 
> thanox用的是智能冻结,没开活检解冻的话会显示 `已被IT管理员禁止`
> 
> 在thanox里全部解冻以后,脚本就正常运行了
> 
> 大佬顺便说一下,在恢复的时候如果应用名单里有MT管理器,就会停止MT的运行,虽然最终还是可以恢复安装,但数据就恢复不了,需要手动解压覆盖,感觉默认排除掉MT的包名会更好些

方便來我群內測試嗎？我剛剛工作之餘改好了

**Comment by tanmoumou252** [comment]
> > > > 5.9.4版本解冻后停止脚本，貌似和Thanox Pro的冻结冲突。就会出现一直无法运行脚本的情况，只有在Thanox Pro中手动解冻所以应用后才能正常运行脚本。 因此，能否加个选项，解冻后继续运行脚本，或者直接和之前版本一样不检查冻结应用列表了。
> > > 
> > > 
> > > 我測試沒有這個問題..... 你有運行的截圖嗎 我看下
> > 
> > 
> > ```
> >     [38;5;226m --通知:false    [0m
> >     [38;5;226m ----------------------SpeedBackup---------------------    [0m
> >     [38;5;226m -脚本路径:/storage/emulated/0/Download/speed-backupV15.9.4
> >  -已开机:0天8时31分10秒
> >  -执行时间:2024-08-05 18:22:30
> >  -busybox路径:/data/backup_tools/busybox
> >  -busybox版本:v1.36.1-osm0sis
> >  -appinfo版本:2024-02-09（111）
> >  -脚本版本:V15.9.4
> >  -管理器:45fa1fce:MAGISKSU
> >  -品牌:Redmi
> >  -型号:Redmi K30S 至尊纪念版(apollo)
> >  -闪存颗粒:WDC SDINFDK4-256G(UFS)
> >  -处理器:Qualcomm® Snapdragon™ 865
> >  -RAM: 
> >  -Android版本:13 SDK:33
> >  -内核:4.19.312-perf+
> >  -Selinux状态:严格
> >  -By@YAWAsau
> >  -Support: https://jq.qq.com/?_wv=1027&k=f5clPNC3
> >  -如果当初握住的不是硬币，而是勇者的手......    [0m
> >     [38;5;226m -系统语言环境:简体中文    [0m
> >     [38;5;177m -主用户:0    [0m
> >     [38;5;226m -当前操作为用户0    [0m
> >     [38;5;226m -已解冻被冻结应用    [0m
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 在此之后就没反应了,所谓冻结的应用,也没有被恢复.
> > thanox用的是智能冻结,没开活检解冻的话会显示 `已被IT管理员禁止`
> > 在thanox里全部解冻以后,脚本就正常运行了
> > 大佬顺便说一下,在恢复的时候如果应用名单里有MT管理器,就会停止MT的运行,虽然最终还是可以恢复安装,但数据就恢复不了,需要手动解压覆盖,感觉默认排除掉MT的包名会更好些
> 
> 方便來我群內測試嗎？我剛剛工作之餘改好了

好的,辛苦大佬了
