### ISSUE TITLE
每次都会把英文#打成中文＃，然后脚本还会备份，请求作者也能识别一下中文＃😘

### ISSUE THREAD

**Issue by n337pp** [YAWAsau/backup_script#92]
![Screenshot_20240718_103015.jpg](https://github.com/user-attachments/assets/50a1eb80-2a3f-48da-b053-05f2f6d22f9b)

**Comment by n337pp** [comment]
知道这是一种业余行为，请大家包容一下子哈哈哈哈🤡

**Comment by YAWAsau** [comment]
......不備份不是去列表裡面搞嗎？

**Comment by YAWAsau** [comment]
> ![Screenshot_20240718_103015.jpg](https://private-user-images.githubusercontent.com/68136163/349761375-50a1eb80-2a3f-48da-b053-05f2f6d22f9b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3NzE2NjIsIm5iZiI6MTcyNTc3MTM2MiwicGF0aCI6Ii82ODEzNjE2My8zNDk3NjEzNzUtNTBhMWViODAtMmEzZi00OGRhLWIwNTMtMDVmMmY2ZDIyZjliLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA4VDA0NTYwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlYTI1NWFiZWMxNDU5ZDcwMGFlNTY4ODg4YjUyYzk3ZTAzM2VmN2M3ZGQ2YWVmMzkxZTg4YzdiZDdiMjYxN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tCfEQI1wFn0wwsFUsE3Fu8wqSq6vG323v5nF64gP74I)

已經支持了 最新版本
