### ISSUE TITLE
【功能请求】输出已过滤应用列表

### ISSUE THREAD

**Issue by PDxtXHd** [YAWAsau/backup_script#94]
当前脚本会在log.txt中记录被忽略的应用，并在文件末尾输出已过滤应用数量，但如果想知道具体哪些应用被过滤了只能通过翻日志找然后手动添加进appList.txt
是否可以将被忽略的应用也输出到appList.txt中，并在开头添加注释符号，这样如果不需要备份就不用动，需要添加备份的只要删掉注释符号就可以放进备份列表了

**Comment by YAWAsau** [comment]
> 当前脚本会在log.txt中记录被忽略的应用，并在文件末尾输出已过滤应用数量，但如果想知道具体哪些应用被过滤了只能通过翻日志找然后手动添加进appList.txt 是否可以将被忽略的应用也输出到appList.txt中，并在开头添加注释符号，这样如果不需要备份就不用动，需要添加备份的只要删掉注释符号就可以放进备份列表了

我搞看看 最近工作有點忙

**Comment by PDxtXHd** [comment]
> > 当前脚本会在log.txt中记录被忽略的应用，并在文件末尾输出已过滤应用数量，但如果想知道具体哪些应用被过滤了只能通过翻日志找然后手动添加进appList.txt 是否可以将被忽略的应用也输出到appList.txt中，并在开头添加注释符号，这样如果不需要备份就不用动，需要添加备份的只要删掉注释符号就可以放进备份列表了
> 
> 我搞看看 最近工作有点忙

收到，辛苦啦~

**Comment by YAWAsau** [comment]
> > > 当前脚本会在log.txt中记录被忽略的应用，并在文件末尾输出已过滤应用数量，但如果想知道具体哪些应用被过滤了只能通过翻日志找然后手动添加进appList.txt 是否可以将被忽略的应用也输出到appList.txt中，并在开头添加注释符号，这样如果不需要备份就不用动，需要添加备份的只要删掉注释符号就可以放进备份列表了
> > 
> > 
> > 我搞看看 最近工作有点忙
> 
> 收到，辛苦啦~

已經更新V15.9.5已經完成支持
