### ISSUE TITLE
instagram bakcup 会被检测

### ISSUE THREAD

**Issue by xucongyong** [YAWAsau/backup_script#96]
![image](https://github.com/user-attachments/assets/a33bf01d-3f99-4624-87a0-8c5811f22ace)

android 14

**Comment by YAWAsau** [comment]
腳本版本？我備份恢復都沒事

**Comment by xucongyong** [comment]
> 腳本版本？我備份恢復都沒事

脚本：最新版的。 
系统：android14
instagram：最新版

备份2个账号然后切换也通过了吗？
