### ISSUE TITLE
备份完成在应用文件夹下执行backup.sh会报错

### ISSUE THREAD

**Issue by ErrorGR** [YAWAsau/backup_script#99]
![Screenshot_2024-11-21-14-33-24-859_bin mt plus](https://github.com/user-attachments/assets/b1f7455a-fced-40b0-bbf3-fa6851d3a1d4)
但是我-/data/media/0/SpeedBackup/backup_settings.conf配置中的user已填写为0，为什么这里会报错
[backup_settings.conf.txt](https://github.com/user-attachments/files/17840912/backup_settings.conf.txt)
MD5:2bff69287bb574611770e637d7412bad
SHA256:2f1a4be30e7e2882155764848baaeebb7c1298258b3d15529a6b9e1f2bc9d5d0

**Comment by ErrorGR** [comment]
所有的应用文件夹下的backup.sh都是如此

**Comment by YAWAsau** [comment]
> 所有的应用文件夹下的backup.sh都是如此，脚本版本是V16.2

方便來我群裡測試嗎？

**Comment by YAWAsau** [comment]
> 你认识我的 emmmm 我刚发现我还在数据备份的频道里(Error)，你看看要不你拉我进群？

3353134147
